apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-prometheus-config
  namespace: dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'jaeger'
        static_configs:
          - targets: ['reporting-jaegertracing.dev.svc.cluster.local:14269']
