apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: dev
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ":4317"
          http:
            endpoint: ":4318"
    processors:
      batch:
    exporters:
      logging:
        loglevel: debug
      prometheus:
        endpoint: ":8888"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]

